import { writeFile, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const styleVersion = createHash('sha256').update(await readFile('styles.css')).digest('hex').slice(0, 12);
import { services } from './content.mjs';
import { newHeader, renderHome, renderService, renderServices } from './lead-pages.mjs';
const origin = 'https://countylandscape.co.uk/';
const arrow = '<span aria-hidden="true">↗</span>';
const esc = value => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const link = service => `${service.slug}.html`;
const header = () => newHeader(services);
const footer = () => `<footer><div class="wrap footer-top"><div><a class="footer-wordmark" href="./">COUNTY<span>LANDSCAPES</span></a><p>From the boundary to the back step.<br>All your gardening needs.</p></div><div class="footer-services"><h2>Explore our services</h2>${services.map(s => `<a href="${link(s)}">${esc(s.name)}</a>`).join('')}</div><div class="footer-contact"><h2>Let’s get outside.</h2><a href="tel:+447526024115">07526 024115 ${arrow}</a><a class="email-link" href="mailto:countylandscaping77@gmail.com">countylandscaping77@gmail.com</a><a href="https://www.tiktok.com/@countylandscapes" target="_blank" rel="noopener noreferrer">@countylandscapes on TikTok ${arrow}</a><p>Call with your postcode to check availability in your area.</p></div></div><div class="wrap footer-bottom"><span>© <span id="year">2026</span> County Landscapes</span><a href="privacy.html">Privacy information</a><a href="#main">Back to top ↑</a></div></footer><div class="mobile-contact"><a href="tel:+447526024115">Call 07526 024115</a><a href="contact.html#contact">Free quote ${arrow}</a></div>`;
const document = (title, description, path, main, home = false, extraHead = '') => `<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#163b2d"><link rel="canonical" href="${origin + path}"><meta property="og:site_name" content="County Landscapes"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${origin + path}"><meta property="og:image" content="${origin}assets/logo.png"><meta name="twitter:card" content="summary"><link rel="icon" href="assets/logo.png">${extraHead}<link rel="stylesheet" href="styles.css?v=${styleVersion}"><script src="form-prompts.js" defer></script><script src="script.js" defer></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'HomeAndConstructionBusiness',name:'County Landscapes',url:origin,telephone:'+447526024115',email:'countylandscaping77@gmail.com',logo:origin+'assets/logo.png',sameAs:['https://www.tiktok.com/@countylandscapes']})}</script></head><body>${header(home)}<main id="main">${main}</main>${footer()}</body></html>`;
const faq = items => `<div class="faq-list">${items.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`;
const contact = `<section class="contact section" id="contact"><div class="wrap contact-grid"><div class="contact-copy"><p class="kicker">YOUR GARDEN. YOUR NEXT STEP.</p><h2>Get your free quote</h2><p>You don’t need all the answers before getting in touch. A description of the job and your postcode are a good place to start.</p><a class="contact-phone" href="tel:+447526024115">07526 024115 ${arrow}</a><span class="fine">Call for a free quote, or email the details and any photos below.</span><a class="email-link contact-email" href="mailto:countylandscaping77@gmail.com">countylandscaping77@gmail.com</a><div class="call-note"><span aria-hidden="true">↳</span><p>More than one job in mind?<br>Tell us about the whole garden.</p></div></div><form id="quote-form" action="https://formspree.io/f/mjgnolow" method="POST"><input type="hidden" name="_subject" value="New County Landscapes website enquiry"><p class="kicker">A FEW DETAILS TO GET US STARTED</p><h3>Tell us what you need</h3><p class="form-notice" id="form-notice">Tell us a little about the job and how we can reach you.</p><label for="service">What would you like help with?</label><select id="service" name="service" required><option value="">Choose a category</option>${services.map(s=>`<option>${esc(s.name)}</option>`).join('')}<option>More than one service / other</option></select><p class="service-prompt" id="service-prompt" aria-live="polite">A garden refresh, an overgrown hedge or a fence that needs attention — tell us where to begin.</p><div class="form-row"><label>Your name<input name="name" autocomplete="name" required placeholder="Full name"></label><label>Phone number<input name="phone" type="tel" autocomplete="tel" required placeholder="Best number to reach you"></label></div><div class="form-row"><label>Email <span>(optional)</span><input name="email" type="email" autocomplete="email" placeholder="you@example.com"></label><label>Postcode<input name="postcode" autocomplete="postal-code" required placeholder="Where is the job?"></label></div><label>Tell us about the job<textarea id="project-message" name="message" rows="4" required placeholder="What needs doing, approximate size and anything useful to know about access."></textarea></label><label>When are you thinking? <span>(optional)</span><select name="timing"><option value="">Select a timeframe</option><option>As soon as availability allows</option><option>Within the next few months</option><option>Planning ahead / flexible</option></select></label><input type="text" name="_gotcha" class="honeypot" tabindex="-1" autocomplete="off" aria-hidden="true"><p class="fine">Your details are for your enquiry. <a href="privacy.html">Read our privacy information</a>.</p><button class="button button-dark" id="submit-quote" type="submit">Request a free quote ${arrow}</button><p id="form-status" role="status" aria-live="polite"></p></form></div></section>`;

const homepage = renderHome(services, contact);

await writeFile('index.html', document('County Landscapes | Garden Services & Free Quotes', 'Garden maintenance, turf, patios, fencing, brickwork, trees, hedges and pressure washing. Explore the work and call County Landscapes on 07526 024115 for a free quote.', '', homepage, true));

for (const service of services) {
  await writeFile(link(service), document(service.name + ' | Free Quotes | County Landscapes', service.summary, link(service), renderService(service, services, contact, faq)));
}
await writeFile('services.html', document('Garden & Outdoor Services | County Landscapes', 'Explore all County Landscapes services and get a free quote.', 'services.html', renderServices(services)));
await writeFile('contact.html', document('Contact County Landscapes | Get a Free Quote', 'Call 07526 024115 or email countylandscaping77@gmail.com for a free quote.', 'contact.html', contact.replace('<h2>Get your free quote</h2>', '<h1>Get your free quote</h1>')));
const privacy = `<section class="section wrap legal"><p class="kicker">COUNTY LANDSCAPES</p><h1>Privacy information</h1><p>This website provides information about County Landscapes and ways to ask about its services.</p><h2>Contacting County Landscapes</h2><p>For enquiries, email <a href="mailto:countylandscaping77@gmail.com">countylandscaping77@gmail.com</a>, call <a href="tel:+447526024115">07526 024115</a>, or use the online enquiry form.</p><h2>Online enquiries</h2><p>When you submit the form, your name, contact details, postcode, chosen service, preferred timing and message are sent through Formspree to County Landscapes so the business can respond to your enquiry. Please only include information needed to discuss the requested work.</p><h2>Website services</h2><p>This website is hosted by GitHub Pages. The hosting provider receives technical information such as your IP address when your browser requests website resources. Formspree processes online enquiry submissions. Fonts are supplied by your device. This website does not add analytics or advertising cookies.</p><h2>External links</h2><p>The TikTok link opens an external service, which has its own privacy practices.</p><h2>Questions</h2><p>If you have a question about information you have shared with County Landscapes, call <a href="tel:+447526024115">07526 024115</a>.</p><p>Last updated: September 2026.</p></section>`;
await writeFile('privacy.html', document('Privacy information | County Landscapes', 'How County Landscapes handles website enquiries and the information you send.', 'privacy.html', privacy));
const notFound = `<section class="section wrap not-found"><div><p class="kicker">404 · PAGE NOT FOUND</p><h1>Let’s get you back to the garden.</h1><p class="lead">The page you followed may have moved. Choose a service below, request a free quote or call County Landscapes.</p><div class="lead-actions"><a class="button button-gold" href="./">Go to the homepage ${arrow}</a><a class="button button-dark" href="contact.html#contact">Get a free quote ${arrow}</a></div><a class="not-found-phone" href="tel:+447526024115">Call 07526 024115</a></div><div class="not-found-links"><h2>What can we help with?</h2>${services.map(s => `<a href="${link(s)}"><span>${esc(s.name)}</span>${arrow}</a>`).join('')}</div></section>`;
await writeFile('404.html', document('Page not found | County Landscapes', 'The requested page could not be found. Explore County Landscapes services or request a free quote.', '404.html', notFound, false, '<meta name="robots" content="noindex,follow">'));
await writeFile('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['', 'services.html', 'contact.html', 'privacy.html', ...services.map(link)].map(p=>`<url><loc>${origin+p}</loc></url>`).join('')}</urlset>`);
await writeFile('robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${origin}sitemap.xml\n`);
await writeFile('form-prompts.js', `window.countyServicePrompts = ${JSON.stringify(Object.fromEntries(services.map(s=>[s.name,s.prompt])))};`);
await writeFile('hedge-trimming.html', document('Hedge cutting, pruning & removal | County Landscapes', 'Hedge cutting, pruning and removal are part of County Landscapes trees and hedges services.', 'tree-surgery.html', '<section class="section wrap"><p class="kicker">TREES &amp; HEDGES</p><h1>Hedge care,<br>all in one place.</h1><p class="lead">Hedge cutting, pruning and removal are now together with tree surgery, stump grinding and root removal in our Trees &amp; hedges category.</p><p style="margin-top:30px"><a class="button button-dark" href="tree-surgery.html">Explore trees &amp; hedges ↗</a></p></section>'));
console.log('Generated site pages, custom 404, sitemap, robots file and enquiry prompts.');
