const esc = value => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const phone = 'tel:+447526024115';
const email = 'mailto:countylandscaping77@gmail.com';
export const serviceImage = s => s.slug === 'tree-surgery' ? 'trees.jpg' : s.slug === 'pressure-washing' ? 'cleaning.jpg' : s.image;
const photo = (s, eager = false) => `<figure class="lead-photo"><img src="assets/${serviceImage(s)}" alt="${esc(s.name)} — temporary illustrative photography from Dee’z Gardens" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'}><figcaption>Illustrative photo · County project photos coming soon</figcaption></figure>`;
const actions = (target = '#contact', label = 'Get a free quote') => `<div class="lead-actions"><a class="button button-gold" href="${target}">${label} ↗</a><a class="button button-dark" href="${phone}">Call 07526 024115</a></div>`;
const band = (target = '#contact') => `<section class="lead-band"><div class="wrap"><div><h2>Need a hand with your garden?</h2><p>One job or a complete change — call for a free quote.</p></div>${actions(target)}</div></section>`;
export const cards = services => `<div class="lead-card-grid">${services.map(s=>`<article class="lead-card"><a href="${s.slug}.html" aria-label="Explore ${esc(s.name)}">${photo(s)}</a><div class="lead-card-body"><h3><a href="${s.slug}.html">${esc(s.name)}</a></h3><p>${s.summary}</p><ul>${s.jobs.map(([name])=>`<li>${esc(name)}</li>`).join('')}</ul><div class="card-actions"><a class="button button-dark" href="${s.slug}.html">View services ↗</a><a class="underlink" href="contact.html?service=${encodeURIComponent(s.name)}#contact">Get a free quote ↗</a></div></div></article>`).join('')}</div>`;
export const newHeader = services => `<a class="skip" href="#main">Skip to content</a><div class="topline"><div class="wrap"><span>FREE QUOTES · GARDEN CARE &amp; LANDSCAPING</span><a href="${phone}">Speak to County: <strong>07526 024115</strong></a></div></div><header class="site-header"><div class="wrap navigation"><a class="brand" href="./" aria-label="County Landscapes home"><img src="assets/logo.png" width="1254" height="1254" alt="County Landscapes"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu ☰</button><nav id="navigation" aria-label="Main navigation"><a href="./">Home</a><details class="services-menu"><summary>Our services</summary><div class="services-dropdown"><a href="services.html">All services</a>${services.map(s=>`<a href="${s.slug}.html">${esc(s.name)}</a>`).join('')}</div></details><a href="contact.html">Contact us</a><a class="nav-phone" href="${phone}">07526 024115</a><a class="button button-gold" href="contact.html#contact">Get a free quote ↗</a></nav></div></header>`;
export function renderHome(services, contact) {
 return `<section class="wrap lead-hero"><div><p class="kicker">COUNTY LANDSCAPES</p><h1>Garden care &amp; landscaping.<br>All in one place.</h1><p class="lead">From lawn mowing and hedge cutting to patios, fencing and tree removal. Tell us what needs doing and get a free quote from County Landscapes.</p>${actions()}<a class="hero-email" href="${email}">Prefer email? countylandscaping77@gmail.com ↗</a><p class="lead-area">Call with your postcode to check availability in your area.</p></div>${photo(services[0], true)}</section><div class="lead-quicklinks"><div class="wrap">${services.map(s=>`<a href="${s.slug}.html">${esc(s.name)} ↗</a>`).join('')}</div></div><section class="section wrap" id="services"><div class="section-heading"><div><p class="kicker">HOW CAN WE HELP?</p><h2>Our garden &amp; outdoor services</h2></div><p>Choose the service you need, see what’s included and contact us for your free quote.</p></div>${cards(services)}</section>${band()}<section class="section wrap lead-about" id="about"><div><h2>One call for the jobs on your list.</h2><p>County Landscapes provides garden maintenance, landscaping, boundary work, tree and hedge services, and outdoor cleaning. You can ask about a single job or discuss several together.</p><p>Need ongoing help? Ask about regular maintenance programmes. Planning a bigger change? Tell us about your priorities, your space and when you’d like the work done.</p>${actions()}</div><div class="lead-benefits"><h3>Let’s get your quote started</h3><ul><li>Tell us which jobs need doing</li><li>Share your postcode and approximate size of the area</li><li>Mention access and your preferred timing</li><li>Discuss the scope and get a free quote</li></ul><a class="underlink" href="${phone}">Speak to County now ↗</a></div></section>${contact}`;
}
export function renderService(s, services, contact, faq) {
 const selectedContact = contact.replace(`<option>${esc(s.name)}</option>`, `<option selected>${esc(s.name)}</option>`);
 return `<section class="wrap lead-hero category-hero"><div><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="./">Home</a><span>/</span><a href="services.html">Services</a><span>/</span><span aria-current="page">${esc(s.name)}</span></nav><h1>${esc(s.name)}</h1><p class="lead">${s.summary}</p>${actions('#contact', `Get a free quote`)}<a class="hero-email" href="${email}">Email your enquiry ↗</a><p class="lead-area">One-off jobs and larger projects — tell us what you need.</p></div>${photo(s,true)}</section><section class="section wrap category-services" id="category-services"><div class="section-heading"><div><h2>${esc(s.name)} services</h2></div><p>Choose the work you need help with. Call us if you have several jobs in mind.</p></div><div class="category-job-grid">${s.jobs.map(([name,description])=>`<article><h3>${esc(name)}</h3><p>${description}</p><div class="job-actions"><a class="button button-dark" href="#contact">Get a free quote ↗</a><a class="underlink" href="${phone}">Call now</a></div></article>`).join('')}</div></section>${band()}<section class="section wrap lead-service-detail"><div><h2>Planning your ${s.short.toLowerCase()}?</h2><p>${s.intro}</p><p>${s.quote}</p><a class="button button-dark" href="#contact">Discuss your job ↗</a></div><div class="lead-benefits"><h3>Helpful details for your quote</h3><ul>${s.checklist.map(x=>`<li>${x}</li>`).join('')}</ul><p>Don’t have every detail? Give us a call and we’ll talk it through.</p></div></section><section class="section wrap faq-section"><div><h2>Your questions answered</h2><a class="underlink" href="${phone}">Ask us directly ↗</a></div>${faq(s.faqs)}</section>${selectedContact}<section class="section wrap"><div class="section-heading"><h2>Need anything else doing?</h2><a class="underlink" href="services.html">All services ↗</a></div>${cards(services.filter(x=>x.slug!==s.slug))}</section>`;
}
export const renderServices = services => `<section class="section wrap"><div class="section-heading"><div><p class="kicker">COUNTY LANDSCAPES</p><h1>Our services</h1></div><p>Garden maintenance, landscaping, fencing, trees, hedges and outdoor cleaning. Choose your service below or call to discuss the whole job.</p></div>${actions('contact.html#contact')}${cards(services)}</section>${band('contact.html#contact')}`;
